#!/bin/sh

AESD_MODULES_DIR="/lib/modules/aesd-modules"

case "$1" in
    # Start case -- LOAD MODULES
    start)
        echo "Loading faulty driver, scull driver and hello module"
        #call module_load and scull_load and modprobe hello module
	cd ${AESD_MODULES_DIR}/scull && ./scull_load
	cd ${AESD_MODULES_DIR}/misc-modules && ./module_load faulty
	cd ${AESD_MODULES_DIR}/misc-modules && modprobe hello.ko 
        ;;
    # Stop case -- UNLOAD MODULES
    stop)
        echo "Unloading faulty driver, scull driver and hello module"
        #call module_unload and scull_unload and rmmod hello module
	cd ${AESD_MODULES_DIR}/scull && ./scull_unload
        cd ${AESD_MODULES_DIR}/misc-modules && ./module_unload faulty 
        cd ${AESD_MODULES_DIR}/misc-modules && rmmod hello.ko
	;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac
